routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminIndex;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\AdboxController;
use App\Http\Controllers\AdContactController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/movie', [HomeController::class,'index'] )->name('movie');
// Route::get('/testmovie', [HomeController::class,'testPage'])->name('testmovie');
Route::get('/', [HomeController::class,'home'] )->name('home');
Route::get('/movies/{id}', [HomeController::class,'show'] )->name('show.movie');
Route::post('/movies/search', [HomeController::class,'search'] )->name('search.movie');
Route::get('/page/{current_page}', [HomeController::class,'pages'] )->name('pages.movie');
Route::get('/contact', [HomeController::class,'contact'])->name('contact');
Route::post('/contact', [HomeController::class,'contactsubmit'])->name('contact.submit');
// Route::get('/', function () {
//     return view('IndexFirst');
// })->name('landingpage');

Route::get('/dashboard', function () {
    return redirect()->route('admin.index');
})->middleware(['auth'])->name('dashboard');

// admin pages
Route::middleware(['auth', 'verified', 'can:admin-access'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', AdminIndex::class)->name('index');

    // roles & permissions
    Route::resource('/permissions', PermissionController::class)->except(['show']);
    Route::resource('/roles', RoleController::class)->except(['show']);

    // users
    Route::resource('/users', UserController::class)->except(['show']);

    // blogs | comment this route below to disable Blog features
    Route::resource('/blogs', BlogController::class);
    Route::resource('/adbox', AdboxController::class);
    Route::resource('/adcontact', AdContactController::class);
   
    // bulk delete
    Route::delete('/bulk-delete/permissions', [PermissionController::class, 'massDestroy'])->name('permissions.massDestroy');
    Route::delete('/bulk-delete/roles', [RoleController::class, 'massDestroy'])->name('roles.massDestroy');
    Route::delete('/bulk-delete/users', [UserController::class, 'massDestroy'])->name('users.massDestroy');
    Route::delete('/bulk-delete/blogs', [BlogController::class, 'massDestroy'])->name('blogs.massDestroy');
    Route::delete('/bulk-delete/adbox', [AdboxController::class, 'massDestroy'])->name('adbox.massDestroy');
    Route::delete('/bulk-delete/adcontact', [AdContactController::class, 'massDestroy'])->name('adcontact.massDestroy');
    
});

// account re-verification
Route::middleware(['verified'])->group(function() {
    Route::get('account/verify-new-email/{token}', [AccountController::class, 'verifyNewEmail'])->name('account.verifyNewEmail');
    Route::resource('account', AccountController::class)->only(['index', 'edit', 'update']);
});

require __DIR__ . '/auth.php';

app/Models/AdContact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AdContact extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/AdContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\AdContact;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class AdContactController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('can:blogs-create')->only(['create', 'store']);
        $this->middleware('can:blogs-read')->only(['index', 'show']);
        $this->middleware('can:blogs-update')->only(['edit', 'update']);
        $this->middleware('can:blogs-delete')->only(['destroy', 'massDestroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $adcontacts = AdContact::latest()->get();

        return view('adcontact.index', compact('adcontacts'));
    }
    
    public function show($id)
    {
        $adcontact = AdContact::findOrFail($id);

        return view('adcontact.show', compact('adcontact'));
    }
    public function destroy($id)
    {
        $adcontact = AdContact::findOrFail($id);
    
        $adcontact->delete();

        return redirect()->route('admin.adcontact.index')->with('success', 'Messages deleted !');
    }

    public function massDestroy(Request $request)
    {
        $arr = explode(',', $request->ids);

        foreach ($arr as $id) {
            $adcontact = AdContact::findOrFail($id);
            $adcontact->delete();
        }

        return redirect()->route('admin.adcontact.index')->with('success', 'Messages deleted !');
    }
}

resources/views/adcontact/index.blade.php
@extends('layouts.adminlte', [
    'title' => 'Blogs'
])

@section('head')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="https://cdn.datatables.net/select/1.3.4/css/select.dataTables.min.css">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp">
@endsection

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <x-adminlte.session-notifications />
            <div class="row mb-2">
                <div class="col-sm-6 d-flex align-items-center">
                    <h1 class="m-0">Messages From Visitors</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
                        <li class="breadcrumb-item active">Ads Contacts Messages</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content pb-3">
        <div class="container-fluid">
            <div class="card m-0">
                <div class="card-body table-responsive">
                    <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th style="cursor: pointer" id="selector">
                                    <input type="checkbox" class="w-100" style="cursor: pointer">
                                    <span style="display: none;">Selector</span>
                                </th>
                                <th>Sender Name</th>
                                <th>Sender Email</th>
                                <th>Message</th>
                                <th>Sending At</th>
                                <th class="d-print-none">Options</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($adcontacts as $adcontact)
                                <tr data-identifier="{{ $adcontact->id }}">
                                    <td></td>
                                    <td>{{ $adcontact->name }}</td>
                                    <td>{{ $adcontact->email }}</td>
                                    <td>{{ $adcontact->message }}</td>
                                    <td>{{ $adcontact->created_at->diffForHumans() }}</td>
                                    <td>
                                        <div class="d-flex flex-column flex-md-row justify-content-center"
                                            style="gap: 0.5rem">
                                            @can('blogs-read')
                                                <a href="{{ route('admin.adcontact.show', $adcontact->id) }}"
                                                    class="btn btn-sm btn-secondary">Preview</a>
                                            @endcan
                                            {{-- @can('blogs-update')
                                                <a href="{{ route('admin.adcontact.edit', $adcontact->id) }}"
                                                    class="btn btn-sm btn-secondary">Edit</a>
                                            @endcan --}}
                                            @can('blogs-delete')
                                                <span class="btn btn-sm btn-danger" id="deleteButton">Delete</span>
                                            @endcan
                                        </div>
                                    </td>
                                    <form action="{{ route('admin.adcontact.destroy', $adcontact->id) }}" method="post"
                                        id="destroy-{{ $adcontact->id }}" style="display: none">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form action="{{ route('admin.adcontact.massDestroy') }}" id="deleteSelectedForm" method="POST" class="d-none">
        @csrf
        @method('DELETE')
        <input type="text" name="ids" id="ids">
    </form>
@endsection

@section('script')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    {{-- <script src="{{ asset('adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script> --}}
    <script src="{{ asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/pdfmake/pdfmake.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/pdfmake/vfs_fonts.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
    <script src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js"></script>
    <script src="{{ asset('js/datatables/select-deselect-all.js') }}"></script>
    <script src="{{ asset('js/datatables/delete-button-init.js') }}"></script>
    <script src="{{ asset('js/datatables/bulk-delete.js') }}"></script>
    <script>
        $(document).ready(function() {
            const exportOption = [1, 2];
            const buttons = [{
                extend: 'copy',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'csv',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'excel',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'pdf',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'print',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                text: 'Delete',
                className: 'btn btn-xs rounded-0 btn-danger',
                action: function() {
                    checkSelectedRows()
                }
            }, ];

            const datatable = $('#datatable').DataTable({
                dom: "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
                    "<'row'<'col-sm-12'B>>" +
                    "<'row'<'col-sm-12'tr>>" +
                    "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
                buttons: buttons,
                select: {
                    style: 'multi',
                    selector: 'td:first-child'
                },
                columnDefs: [{
                    orderable: false,
                    className: 'select-checkbox',
                    targets: 0
                }, {
                    orderable: false,
                    targets: 3
                }],
            });

            const selectAll = () => datatable.rows().select();
            const deselectAll = () => datatable.rows().deselect();

            const selections = document.querySelector('#selections');
            const checkbox = selections.querySelector('input');

            const checkAction = () => {
                if (checkbox.checked) {
                    checkbox.checked = false;
                    deselectAll();
                } else {
                    checkbox.checked = true;
                    selectAll();
                }
            }

            selections.addEventListener('click', () => {
                checkAction();
            });

            checkbox.addEventListener('click', () => {
                checkAction();
            });
        })
    </script>
    <script>
        // delete data
        const deleteButtons = document.querySelectorAll('#deleteButton');
        deleteButtons.forEach(button => {
            button.addEventListener('click', () => {
                swal({
                        title: "Are you sure?",
                        text: "Once deleted, you will not be able to recover this data!",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            let identifier = button.parentElement.parentElement.parentElement.dataset
                                .identifier;
                            document.querySelector(`#destroy-${identifier}`).submit()
                        } else {
                            // swal("Your data is safe!");
                        }
                    });
            })
        });
    </script>
    <script>
        // mass delete
        const checkSelectedRows = () => {
            const deleteSelectedForm = document.querySelector('#deleteSelectedForm');
            const ids = document.querySelector('#deleteSelectedForm input#ids');
            let selectedRowsArr = []
            let selectedRows = document.querySelectorAll('tr.selected');
            selectedRows.forEach(row => {
                selectedRowsArr.push(row.dataset.identifier);
            });

            @can('standards delete')
                if (selectedRowsArr.length == 0) {
                    swal({
                        title: "0 Data selected",
                        text: "Please select minimal 1 data!",
                        icon: "error",
                    });
                } else {
                    swal({
                        title: "Are you sure?",
                        text: "Once deleted, you will not be able to recover your datas!",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    }).then((willDelete) => {
                        if (willDelete) {
                            ids.value = selectedRowsArr;
                            deleteSelectedForm.submit();
                        } else {
                            //
                        }
                    })
                }
            @else
                swal({
                    title: "Action denied",
                    text: "You don't have permission to do this action!",
                    icon: "error",
                });
            @endcan
        }
    </script>
@endsection

resources/views/adcontact/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        <a href="{{route('admin.adcontact.index')}}">Back to Dashboard</a>
        <h1> Sender : {{$adcontact->name}} - {{$adcontact->email}} </h1>
        {!! $adcontact->message !!}
    </div>
</body>
</html>