routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminIndex;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\AdboxController;
use App\Http\Controllers\AdContactController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/movie', [HomeController::class,'index'] )->name('movie');
// Route::get('/testmovie', [HomeController::class,'testPage'])->name('testmovie');
Route::get('/', [HomeController::class,'home'] )->name('home');
Route::get('/movies/{id}', [HomeController::class,'show'] )->name('show.movie');
Route::post('/movies/search', [HomeController::class,'search'] )->name('search.movie');
Route::get('/page/{current_page}', [HomeController::class,'pages'] )->name('pages.movie');
Route::get('/contact', [HomeController::class,'contact'])->name('contact');
Route::post('/contact', [HomeController::class,'contactsubmit'])->name('contact.submit');
// Route::get('/', function () {
//     return view('IndexFirst');
// })->name('landingpage');

Route::get('/dashboard', function () {
    return redirect()->route('admin.index');
})->middleware(['auth'])->name('dashboard');

// admin pages
Route::middleware(['auth', 'verified', 'can:admin-access'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', AdminIndex::class)->name('index');

    // roles & permissions
    Route::resource('/permissions', PermissionController::class)->except(['show']);
    Route::resource('/roles', RoleController::class)->except(['show']);

    // users
    Route::resource('/users', UserController::class)->except(['show']);

    // blogs | comment this route below to disable Blog features
    Route::resource('/blogs', BlogController::class);
    Route::resource('/adbox', AdboxController::class);
    Route::resource('/adcontact', AdContactController::class);
   
    // bulk delete
    Route::delete('/bulk-delete/permissions', [PermissionController::class, 'massDestroy'])->name('permissions.massDestroy');
    Route::delete('/bulk-delete/roles', [RoleController::class, 'massDestroy'])->name('roles.massDestroy');
    Route::delete('/bulk-delete/users', [UserController::class, 'massDestroy'])->name('users.massDestroy');
    Route::delete('/bulk-delete/blogs', [BlogController::class, 'massDestroy'])->name('blogs.massDestroy');
    Route::delete('/bulk-delete/adbox', [AdboxController::class, 'massDestroy'])->name('adbox.massDestroy');
    Route::delete('/bulk-delete/adcontact', [AdContactController::class, 'massDestroy'])->name('adcontact.massDestroy');
    
});

// account re-verification
Route::middleware(['verified'])->group(function() {
    Route::get('account/verify-new-email/{token}', [AccountController::class, 'verifyNewEmail'])->name('account.verifyNewEmail');
    Route::resource('account', AccountController::class)->only(['index', 'edit', 'update']);
});

require __DIR__ . '/auth.php';

app/Models/Adbox.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Adbox extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/AdboxController.php
<?php

namespace App\Http\Controllers;

use App\Models\AdBox;
use DOMDocument;
use Illuminate\Http\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;
use Intervention\Image\ImageManagerStatic as Image;
class AdboxController extends Controller
{
    //

    public function __construct()
    {
        $this->middleware('can:blogs-create')->only(['create', 'store']);
        $this->middleware('can:blogs-read')->only(['index', 'show']);
        $this->middleware('can:blogs-update')->only(['edit', 'update']);
        $this->middleware('can:blogs-delete')->only(['destroy', 'massDestroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $adboxs = AdBox::latest()->get();

        return view('adbox.index', compact('adboxs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adbox.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'ads_name' => ['required'],
            'expires_at' => ['required'],
            'url_file' => ['required','image','mimes:jpeg,png,jpg,gif'],
        ]);

        $file = $request->file('url_file');
        $path = Storage::disk('public')->putFile('adbox_banner', new File($file));

        // return $imageName;
        
        $adBox = AdBox::create([
            'ads_name' => $request->ads_name,
            'status' => 'approved ads',
            'expires_at' => $request->expires_at,
            'url_file' => $path,
        ]);


        return redirect()->route('admin.adbox.index')->with('success', 'adbox uploaded !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
     
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $adbox = AdBox::findOrFail($id);
        if (Storage::disk('public')->exists($adbox->url_file)) {
            Storage::disk('public')->delete($adbox->url_file);
        }
        $adbox->delete();

        return redirect()->route('admin.adbox.index')->with('success', 'adbox deleted !');
    }

    public function massDestroy(Request $request)
    {
        $arr = explode(',', $request->ids);

        foreach ($arr as $id) {
            $adbox = AdBox::findOrFail($id);
            if (Storage::disk('public')->exists($adbox->url_file)) {
                Storage::disk('public')->delete($adbox->url_file);
            }
            $adbox->delete();
        }

        return redirect()->route('admin.adbox.index')->with('success', 'Ads deleted !');
    }
}

resources/views/adbox/create.blade.php
@extends('layouts.adminlte')

@section('head')
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp">
    <style>
        .ck-editor__editable_inline {
            min-height: 400px;
        }

    </style>
@endsection

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 d-flex align-items-center">
                    <h1 class="m-0">Create Blog</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.adbox.index') }}">adbox</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content pb-3">
        <div class="container-fluid">
            <div class="card m-0">
                <div class="card-body">
                    <form action="{{ route('admin.adbox.store') }}" enctype="multipart/form-data" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="ads_name" class="text-capitalize">ADS NAME</label>
                            <input type="text" class="form-control" id="ads_name" name="ads_name" placeholder="input name for the Ads Here"
                                value="{{ old('ads_name') }}" required>
                            @error('ads_name')
                                <div class="text-sm text-danger">{{ $message ?? 'Something error' }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="expires_at" class="text-capitalize">expires_at</label><br>
                            <input type="date" class="form-control w-50" id="expires_at" name="expires_at">
                        </div>
                        <div class="form-group">
                            <label for="url_file" class="text-capitalize">Upload Image</label><br>
                            <b class="text-danger">*Image Width x Height Recommended :  650px x 220px </b><br>
                            <b class="text-danger">*format support : jpeg, jpg, png, gif </b>
                            <input type="file" class="form-control" id="url_file" name="url_file">
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('ckeditor5/build/ckeditor.js') }}"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#body'), {

                licenseKey: '',



            })
            .then(editor => {
                window.editor = editor;




            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error(
                    'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:'
                );
                console.warn('Build id: 8ubb9kaqv8bd-mk6bg6wswnw1');
                console.error(error);
            });
    </script>
@endsection

resources/views/adbox/edit.blade.php
@extends('layouts.adminlte')

@section('head')
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp">
    <style>
        .ck-editor__editable_inline {
            min-height: 400px;
        }

    </style>
@endsection

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 d-flex align-items-center">
                    <h1 class="m-0">Edit Blog</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.blogs.index') }}">Blogs</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content pb-3">
        <div class="container-fluid">
            <div class="card m-0">
                <div class="card-body">
                    <form action="{{ route('admin.blogs.update', $blog) }}" method="POST">
                        @csrf
                        @method('PATCH')
                        <div class="form-group">
                            <label for="title" class="text-capitalize">title</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Some Title Here"
                                value="{{ old('title') ?? $blog->title }}" required>
                            @error('title')
                                <div class="text-sm text-danger">{{ $message ?? 'Something error' }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="body" class="text-capitalize">body</label>
                            <textarea name="body" id="body" rows="10" class="form-control">{{ old('body') ?? $blog->body }}</textarea>
                            @error('body')
                                <div class="text-sm text-danger">{{ $message ?? 'Something error' }}</div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('ckeditor5/build/ckeditor.js') }}"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#body'), {

                licenseKey: '',



            })
            .then(editor => {
                window.editor = editor;




            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error(
                    'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:'
                );
                console.warn('Build id: 8ubb9kaqv8bd-mk6bg6wswnw1');
                console.error(error);
            });
    </script>
@endsection

resources/views/adbox/index.blade.php
@extends('layouts.adminlte', [
    'title' => 'Blogs'
])

@section('head')
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="https://cdn.datatables.net/select/1.3.4/css/select.dataTables.min.css">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp">
@endsection

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <x-adminlte.session-notifications />
            <div class="row mb-2">
                <div class="col-sm-6 d-flex align-items-center">
                    <h1 class="m-0">Adbox</h1>
                    @can('blogs-create')
                        <a href="{{ route('admin.adbox.create') }}" class="btn btn-sm btn-primary ml-2">Add New</a>
                    @endcan
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Home</a></li>
                        <li class="breadcrumb-item active">Adbox</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content pb-3">
        <div class="container-fluid">
            <div class="card m-0">
                <div class="card-body table-responsive">
                    <table id="datatable" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th style="cursor: pointer" id="selector">
                                    <input type="checkbox" class="w-100" style="cursor: pointer">
                                    <span style="display: none;">Selector</span>
                                </th>
                                <th>Ads Name</th>
                                <th>Image</th>
                                <th>Status</th>
                                <th>expires at</th>
                                <th>Created At</th>
                                <th class="d-print-none">Options</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($adboxs as $adbox)
                                <tr data-identifier="{{ $adbox->id }}">
                                    <td></td>
                                    <td>{{ $adbox->ads_name }}</td>
                                    <td><img style="object-fit: cover !important;width:650px;height:220px;" src="{{ Storage::disk('public')->url(@$adbox->url_file) }}" alt=""></td>
                                    <td>
                                        @if (\Carbon\Carbon::now() >= $adbox->expires_at)
                                            <b class="text-danger">EXPIRED</b>
                                        @else
                                            <b class="text-success">PUBLISH</b>
                                        @endif
                                    </td>
                                    <td>{{ $adbox->expires_at }}</td>
                                    <td>{{ $adbox->created_at->diffForHumans() }}</td>
                                    <td>
                                        <div class="d-flex flex-column flex-md-row justify-content-center"
                                            style="gap: 0.5rem">
                                            {{-- @can('blogs-read')
                                                <a href="{{ route('admin.adbox.show', $adbox->id) }}"
                                                    class="btn btn-sm btn-secondary">Preview</a>
                                            @endcan
                                            @can('blogs-update')
                                                <a href="{{ route('admin.adbox.edit', $adbox->id) }}"
                                                    class="btn btn-sm btn-secondary">Edit</a>
                                            @endcan --}}
                                            @can('blogs-delete')
                                                <span class="btn btn-sm btn-danger" id="deleteButton">Delete</span>
                                            @endcan
                                        </div>
                                    </td>
                                    <form action="{{ route('admin.adbox.destroy', $adbox->id) }}" method="post"
                                        id="destroy-{{ $adbox->id }}" style="display: none">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form action="{{ route('admin.adbox.massDestroy') }}" id="deleteSelectedForm" method="POST" class="d-none">
        @csrf
        @method('DELETE')
        <input type="text" name="ids" id="ids">
    </form>
@endsection

@section('script')
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    {{-- <script src="{{ asset('adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script> --}}
    <script src="{{ asset('adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/pdfmake/pdfmake.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/pdfmake/vfs_fonts.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
    <script src="https://cdn.datatables.net/select/1.3.3/js/dataTables.select.min.js"></script>
    <script src="{{ asset('js/datatables/select-deselect-all.js') }}"></script>
    <script src="{{ asset('js/datatables/delete-button-init.js') }}"></script>
    <script src="{{ asset('js/datatables/bulk-delete.js') }}"></script>
    <script>
        $(document).ready(function() {
            const exportOption = [1, 2];
            const buttons = [{
                extend: 'copy',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'csv',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'excel',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'pdf',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                extend: 'print',
                className: 'btn btn-xs rounded-0 btn-secondary',
                exportOptions: {
                    columns: exportOption
                }
            }, {
                text: 'Delete',
                className: 'btn btn-xs rounded-0 btn-danger',
                action: function() {
                    checkSelectedRows()
                }
            }, ];

            const datatable = $('#datatable').DataTable({
                dom: "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
                    "<'row'<'col-sm-12'B>>" +
                    "<'row'<'col-sm-12'tr>>" +
                    "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
                buttons: buttons,
                select: {
                    style: 'multi',
                    selector: 'td:first-child'
                },
                columnDefs: [{
                    orderable: false,
                    className: 'select-checkbox',
                    targets: 0
                }, {
                    orderable: false,
                    targets: 3
                }],
            });

            const selectAll = () => datatable.rows().select();
            const deselectAll = () => datatable.rows().deselect();

            const selections = document.querySelector('#selections');
            const checkbox = selections.querySelector('input');

            const checkAction = () => {
                if (checkbox.checked) {
                    checkbox.checked = false;
                    deselectAll();
                } else {
                    checkbox.checked = true;
                    selectAll();
                }
            }

            selections.addEventListener('click', () => {
                checkAction();
            });

            checkbox.addEventListener('click', () => {
                checkAction();
            });
        })
    </script>
    <script>
        // delete data
        const deleteButtons = document.querySelectorAll('#deleteButton');
        deleteButtons.forEach(button => {
            button.addEventListener('click', () => {
                swal({
                        title: "Are you sure?",
                        text: "Once deleted, you will not be able to recover this data!",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            let identifier = button.parentElement.parentElement.parentElement.dataset
                                .identifier;
                            document.querySelector(`#destroy-${identifier}`).submit()
                        } else {
                            // swal("Your data is safe!");
                        }
                    });
            })
        });
    </script>
    <script>
        // mass delete
        const checkSelectedRows = () => {
            const deleteSelectedForm = document.querySelector('#deleteSelectedForm');
            const ids = document.querySelector('#deleteSelectedForm input#ids');
            let selectedRowsArr = []
            let selectedRows = document.querySelectorAll('tr.selected');
            selectedRows.forEach(row => {
                selectedRowsArr.push(row.dataset.identifier);
            });

            @can('standards delete')
                if (selectedRowsArr.length == 0) {
                    swal({
                        title: "0 Data selected",
                        text: "Please select minimal 1 data!",
                        icon: "error",
                    });
                } else {
                    swal({
                        title: "Are you sure?",
                        text: "Once deleted, you will not be able to recover your datas!",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    }).then((willDelete) => {
                        if (willDelete) {
                            ids.value = selectedRowsArr;
                            deleteSelectedForm.submit();
                        } else {
                            //
                        }
                    })
                }
            @else
                swal({
                    title: "Action denied",
                    text: "You don't have permission to do this action!",
                    icon: "error",
                });
            @endcan
        }
    </script>
@endsection

resources/views/adbox/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        {!! $blog->body !!}
    </div>
</body>
</html>